import type { SVGProps } from "react";

export function ZeronIcon(props: SVGProps<SVGSVGElement>) {
  return (
    <svg
      width="67"
      height="73"
      viewBox="0 0 67 73"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <line
        x1="2.5"
        y1="2.5"
        x2="63.5"
        y2="2.49999"
        stroke="currentColor"
        stroke-width="5"
        stroke-linecap="round"
      />
      <line
        x1="2.5"
        y1="2.5"
        x2="2.5"
        y2="70.5"
        stroke="currentColor"
        stroke-width="5"
        stroke-linecap="round"
      />
      <line
        x1="64.5"
        y1="2.5"
        x2="64.5"
        y2="70.5"
        stroke="currentColor"
        stroke-width="5"
        stroke-linecap="round"
      />
      <line
        x1="12.5"
        y1="4.5"
        x2="12.5"
        y2="68.5"
        stroke="currentColor"
        stroke-width="5"
        stroke-linecap="round"
      />
      <line
        x1="54.5838"
        y1="3.42739"
        x2="15.4274"
        y2="69.1323"
        stroke="currentColor"
        stroke-width="5"
        stroke-linecap="round"
      />
      <line
        x1="54.5"
        y1="4.5"
        x2="54.5"
        y2="68.5"
        stroke="currentColor"
        stroke-width="5"
        stroke-linecap="round"
      />
      <line
        x1="2.5"
        y1="70.5"
        x2="63.5"
        y2="70.5"
        stroke="currentColor"
        stroke-width="5"
        stroke-linecap="round"
      />
    </svg>
  );
}
